
== Formål, omfang og avgrensninger

Denne standarden skal sikre at begrepsbeskrivelser som forvaltes av offentlig forvaltning, tilgjengeliggjøres på en standardisert og maskinlesbar måte.

Standarden spesifiserer hvordan begrepsbeskrivelser som er utformet i henhold til https://www.digdir.no/digitale-felleslosninger/forvaltningsstandard-begrepsbeskrivelser/1649[_Forvaltningsstandard for begrepsbeskrivelser_], gjøres tilgjengelig i maskinlesbare formater i henhold til TBX-standarden. Standarden spesifiserer ikke krav til innhold i en begrepsbeskrivelse, heller ikke krav til et eventuelt IT-system for å forvalte begrepsbeskrivelser.

Standarden brukes når en virksomhet skal tilgjengeliggjøre begrepsbeskrivelser som de selv forvalter, i et maskinlesbart format og i henhold til TBX-standarden. Se ellers https://www.digdir.no/digitalisering-og-samordning/begrepsanalyse-og-definisjonsarbeid/1483[bruksområde “Begrepsanalyse og definisjonsarbeid”] i _Referansekatalogen_ for andre aktuelle standarder og veiledere.
