name: build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      update-submodules: false
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/tbx-ap-no-v1.pdf -a lang=nb docs/main.adoc
      files: |
        docs/index.html text/html nb
        docs/files/tbx-ap-no-v1.pdf application/pdf nb files/tbx-ap-no.pdf
        docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
      host: https://fellesdatakatalog.digdir.no
      ontology: tbx-ap-no
      ontology-type: specification
      version: v1
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}