name: Build adocs and publish v2 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v2
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v2
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/tbx-ap-no.pdf -a lang=nb docs/main.adoc
      files: |
        docs/index.html text/html nb
        docs/files/tbx-ap-no.pdf application/pdf nb files/tbx-ap-no.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/TBX-AP-NO_Begrepssamling.png image/png nb images/TBX-AP-NO_Begrepssamling.png
        docs/images/TBX-AP-NO_conceptEntry.png image/png nb images/TBX-AP-NO_conceptEntry.png
        docs/images/TBX-AP-NO_langSec.png image/png nb images/TBX-AP-NO_langSec.png
      host: https://fellesdatakatalog.digdir.no
      ontology: tbx-ap-no
      ontology-type: specification
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
